analytics: {}
color:
  brandColors:
    - '#f1720d'
    - '#b5182b'
    - '#056b36'
    - '#05ad1e'
    - '#6e6023'
  brandStrength: 0.5
  lightness: 0.5
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 0.771115
name: Shahzad Khaliq
opengraph: {}
purpose: []
typography_spectrum: 0.7734
