analytics: {}
color:
  brandColors:
    - '#000000'
    - '#7040A0'
    - '#8050B0'
    - '#38B0E0'
    - '#50A0E0'
  brandStrength: 0.327703
  lightness: 0.401182
  rhythmicContrast: 0.511824
  saturation: 0.279561
cta: {}
layout_spectrum: 0.419764
name: Shahzad Khaliq
opengraph: {}
purpose: []
typography_spectrum: 0.804899
