name: Shahzad Khaliq
favicon: null
layout_spectrum: 0.4966988214291632
typography_spectrum: 0.09409223799593747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3663744640070945
  lightness: 0.5869342975784093
  saturation: 0.06164489942602813
  rhythmicContrast: 0.333193740574643
purpose: []
