name: Shahzad Khaliq
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7734
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1720d'
    - '#b5182b'
    - '#056b36'
    - '#05ad1e'
    - '#6e6023'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
